DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS documents;

CREATE TABLE documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(512) NOT NULL,
    file_path   VARCHAR(1024),
    chunk_count INT NOT NULL DEFAULT 0,
    status      VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    error_msg   VARCHAR(1024),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    seq         INT NOT NULL,
    content     TEXT NOT NULL,
    CONSTRAINT fk_chunks_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT uq_chunks_document_seq UNIQUE (document_id, seq)
);

CREATE INDEX idx_chunks_document_id ON chunks(document_id);
CREATE INDEX idx_documents_created_at ON documents(created_at DESC);
